# Generated by Django 6.0 on 2025-12-19 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='vendas',
            field=models.IntegerField(default=0),
        ),
    ]
